// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_flavors/test/mock/mock_remote_configuration_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_remote_config/firebase_remote_config.dart' as _i2;
import 'package:flutter_flavors/repositories/remote_config_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseRemoteConfig_0 extends _i1.SmartFake
    implements _i2.FirebaseRemoteConfig {
  _FakeFirebaseRemoteConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigRepository extends _i1.Mock
    implements _i3.RemoteConfigRepository {
  @override
  _i2.FirebaseRemoteConfig get remoteConfig => (super.noSuchMethod(
        Invocation.getter(#remoteConfig),
        returnValue: _FakeFirebaseRemoteConfig_0(
          this,
          Invocation.getter(#remoteConfig),
        ),
        returnValueForMissingStub: _FakeFirebaseRemoteConfig_0(
          this,
          Invocation.getter(#remoteConfig),
        ),
      ) as _i2.FirebaseRemoteConfig);

  @override
  bool get showDaysView => (super.noSuchMethod(
        Invocation.getter(#showDaysView),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> configure() => (super.noSuchMethod(
        Invocation.method(
          #configure,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getWelcomeMessage() => (super.noSuchMethod(
        Invocation.method(
          #getWelcomeMessage,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getWelcomeMessage,
            [],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getWelcomeMessage,
            [],
          ),
        ),
      ) as String);
}
