name: flutter_flavors
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/common/
    - path: assets/dev/
      flavors:
        - dev
    - path: assets/app1/
      flavors:
        - app1
    - path: assets/app2/
      flavors:
        - app2


  uses-material-design: true


